name = "Lotus"
grammar = "lotus"
path_suffixes = ["lo"]
line_comments = ["// "]
block_comments = ["/* ", " */"]
autoclose_before = ",=)]}"
tab_size = 4
brackets = [
    { start = "[", end = "]", close = true, newline = true },
    { start = "{", end = "}", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false },
]
